### ISSUE TITLE
All fields in GInfo show a default value and it cannot be closed.

### ISSUE THREAD

**Issue by Railworks2** [SyncAdmin/Plugins#38]
GInfo looks like this...
![image](https://user-images.githubusercontent.com/27024242/33207878-54fc0c0e-d107-11e7-84b1-f1e51fa7a976.png)
It is not possible to close this window without resetting or leaving the game. (The window is also still moveable)

Known games: https://www.roblox.com/games/1186982515/Sip-N-Chill-Cafe
https://www.roblox.com/games/432409487/Office
https://www.roblox.com/games/430367172/Soros-Italian-Restaurant-Version-3

**Comment by ForPizzaSake** [comment]
This feature is deprecated. 

I've gone ahead and fully removed it.
