### ISSUE TITLE
When scrolling in the settings, the settings window moves.

### ISSUE THREAD

**Issue by Railworks2** [SyncAdmin/Plugins#39]
Issue: When scrolling in the settings command, occurs in all tabs, the whole GUI moves along with the section inside moves. (Refer to gif)

Repo:

- Open Settings
- Scroll as normal
- Observe

Expected result: Only the internal section should scroll.
Actual result: Whole window/GUI moves. ![Gif showing the issue](https://i.gyazo.com/b59ebfc26fd3e2285cea7bc1b7931e15.mp4)

Affected games https://www.roblox.com/games/432409487/Office

Limited testing occured

**Comment by ForPizzaSake** [comment]
Hey there,

This seems to be a Roblox issue, however, I've gone ahead and changed the behavior of the GUI itself. It can not be dragged anymore.

**Comment by Railworks2** [comment]
Looks like it occurs in cmd and most likely other GUI based stuff

**Comment by ForPizzaSake** [comment]
It seems to be a Roblox issue, I'll look into this - just don't expect any fast patch for it.
