### ISSUE TITLE
Cannot unban users due to a mistake in the Unban plugin

### ISSUE THREAD

**Issue by Symplyfyed** [SyncAdmin/Plugins#41]
Hi there!

I want to report an issue.
I couldn't unban users from my game using the !!unban command.

However all I needed to do was removing an "s" from the unban plugin. (module)
![screenshot_2017-12-26-01-59-43](https://user-images.githubusercontent.com/30578614/34343674-10dddf5a-e9e1-11e7-91f0-f59c5012c18c.png)

I think the plugin should be updated because that's how it is by default. So if the users add SyncAdmin to their game they won't be able to unban users unless they take a look at the plugin and find the issue then fix it themselves.

**Comment by ForPizzaSake** [comment]
Hey there, @Symplyfyed 

Thank you for reporting this issue. We will address this issue after the holidays!
However, we're glad you've resolved the issue yourself.

Happy Holidays!

**Comment by Symplyfyed** [comment]
Hi @ForPizzaSake ! Thank you.  Have a nice day and happy holidays! 😃
