### ISSUE TITLE
Offsite Link

### ISSUE THREAD

**Issue by ElliottLMz** [SyncAdmin/Plugins#48]
https://github.com/SyncAdmin/Plugins/blob/master/Custom%20Plugins/Template/SA_Blank_Template has an offsite link to the github, this is agasint the Roblox Community Guidelines.

**Comment by SharpColours** [comment]
This template is on our online GitHub. GitHub terms of service does not state that offsite links are prohibited.

**Comment by ElliottLMz** [comment]
Most people will copy it into Roblox directly, and some people probably wouldn't remove it for future reference.

**Comment by SharpColours** [comment]
That's their perogative. That script is not a .Lua script and is therefore not intended for people to directly copy and paste, they can remove the link.

- SharpColours, SyncAdmin Intern

**Comment by Railworks2** [comment]
N/A. Github is 3rd party and is not covered under the ToS. See section 2.3 Third-Party Services. The TOS is covered under the community guidelines, see section 12 Other activity and the last bullet point.

**Comment by Railworks2** [comment]
(Although thanks for going though and searching for any possible violations)
